### ISSUE TITLE
[Feature] Any plan to support TUNA DNS666 on DoT/DoH?

### ISSUE THREAD

**Issue by leiless** [tuna/tuna.moe#37]
Hi, TUNA group, do you have any plan to support DoT/DoH on TUNA DNS666?

If you guys intend to do so, [https://github.com/m13253/dns-over-https](m13253/dns-over-https) might be a good choice.

Also I recommend you guys to support DoH direct IP access. i.e. `https://$AN_IP_ADDRESS/dns-query`.
For example:
AliDNS: https://223.5.5.5/dns-query
Cloudflare: https://1.1.1.1/dns-query
Google: https://8.8.8.8/dns-query
Quad9: https://9.9.9.9/dns-query

see: [Can I order an SSL/TLS certificate for an IP address?](https://www.ssl.com/faqs/order-ssl-tls-certificate-for-ip-address/)

**Comment by jiegec** [comment]
DNS666 supports these already.

**Comment by shankerwangmiao** [comment]
Hi,

You can try https://101.6.6.6:8443/resolve for JSON based API for https://101.6.6.6:8443/dns-query for RFC8484 compatible API.

Cheers

Miao Wang
