### ISSUE TITLE
更名了（实名认证了）

### ISSUE THREAD

**Issue by alick** [tuna/tuna.moe#4]
是不是可以加上“现名清华大学网络与开源软件协会”（附社团部页面链接）😂

**Comment by bigeagle** [comment]
2333，社团部链接不需要放吧。

## 

Justin Wong

On Mon, May 16, 2016, at 11:03, Alick Zhao wrote:

> 是不是可以加上“现名清华大学网络与开源软件协会”（附社团部页面链接）😂
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub[1]

Links:
1. https://github.com/tuna/tuna.moe/issues/4
